apiVersion: v1
kind: Template
metadata:
  annotations:
    description: Oracle Express Edition 12c R2
  name: oracle-xe-12c-official-template
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: oracle-xe-12c
    name: oracle-xe-12c
  spec:
    lookupPolicy:
      local: false
    tags:
    - name: "12.2.0.1"
      from:
        kind: DockerImage
        name: store/oracle/database-enterprise:12.2.0.1
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: oracle-xe-12c
    name: oracle-xe-12c
  spec:
    replicas: 1
    selector:
      app: oracle-xe-12c
      deploymentconfig: oracle-xe-12c
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: oracle-xe-12c
          deploymentconfig: oracle-xe-12c
      spec:
        containers:
        - image: store/oracle/database-enterprise:12.2.0.1
          imagePullPolicy: IfNotPresent
          name: oracle-xe-12c
          ports:
          - containerPort: 1521
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          livenessProbe:
            exec:
              command:
                - /usr/sbin/healthcheck.sh
            failureThreshold: 3
            initialDelaySeconds: 180
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            exec:
              command:
                - /usr/sbin/healthcheck.sh
            failureThreshold: 3
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          runAsUser: 1000
        serviceAccount: nonroot
        serviceAccountName: nonroot
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - oracle-xe-12c
        from:
          kind: ImageStreamTag
          name: oracle-xe-12c:12.2.0.1
          namespace: openshift
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: oracle-xe-12c
    name: oracle-xe-12c
  spec:
    ports:
    - name: 1521-tcp
      port: 1521
      protocol: TCP
      targetPort: 1521
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: oracle-xe-12c
    sessionAffinity: None
    type: ClusterIP
